blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [path('create/', BlogCreateView.as_view(), name='blog_create'),
               path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
               path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
               path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
               path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete')
               ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', null=True, blank=True)
    count_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')
    date_of_publication = models.DateField(default=timezone.now, verbose_name='дата создания', null=True)

    def __str(self):
        return f'{self.title} {self.date_of_publication} ({self.count_of_views} просм.)'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms

from blog.models import Blog


class BlogCreateForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = '__all__'


class BlogUpdateForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = '__all__'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.forms import BlogCreateForm, BlogUpdateForm
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogCreateForm
    success_url = reverse_lazy('blog:blog_list')
    template_name = 'blog_form.html'


class BlogListView(ListView):
    model = Blog
    template_name = 'blog_list.html'


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog_detail.html'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_of_views += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogUpdateForm
    template_name = 'blog_edit.html'

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    template_name = 'blog_confirm_delete.html'

blog/templates/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<title>Удаление записи</title>
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить блог {{ object.title }}?</p>
                            <button type="submit" name="confirm" value="{{ object.id }}" class="btn btn-warning">Подтвердить</button>
                            <a href="{% url 'blog:blog_list' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog_detail.html
{% extends 'main/base.html' %}
{% load static %}

{% block content%}
<link href={% static 'css/blog_detail_style.css' %} rel="stylesheet">
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div class="article-container">
        Просмотры: {{ object.count_of_views }}
        <img class="card-img-top" src="{{ blog.image.url }}" alt="Card image cap">
        <h1>{{ blog.title }}</h1>
        <p>Дата написания: {{ blog.date_of_publication }}</p>

        <div>
            <p>Содержание статьи:</p>
            <p>{{ blog.body }}</p>
        </div>
    </div>
</body>
</html>

{% endblock %}

blog/templates/blog_edit.html
{% extends 'main/base.html' %}

{% block content %}


<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Изменить</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

blog/templates/blog_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

blog/templates/blog_list.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>

<div class="album py-5 bg-light">
  <a class="btn btn-outline-primary" href="{% url 'blog:blog_create' %}">Добавить запись</a>
  <div class="container">
    <div class="row">
      {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">{{ object.title }}</p>
            <p class="card-text">{{ object.content|truncatechars:100 }}</p>
            <p class="card-text">{{ object.date_of_publication }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'blog:blog_edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

</div>
</html>
{% endblock %}