blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [path('create/', BlogCreateView.as_view(), name='blog_create'),
               path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
               path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
               path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
               path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete')
               ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, VerifyCodeView, success_view, reset_password
from users.models import User

app_name = 'users'

urlpatterns = [path('registration/', UserCreateView.as_view(), name='user_create'),
               path('verify/', VerifyCodeView.as_view(), name='verify_code'),
               path('registration/success/', success_view, name='success_regist'),
               path('login/', LoginView.as_view(template_name='user/user_login.html'), name='login'),
               path('logout/', LogoutView.as_view(template_name='user/user_logout.html'), name='logout'),
               path('reset_password/', reset_password, name='reset_password')]

users/models.py
from django.contrib.auth.models import AbstractUser, PermissionsMixin, Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import models


class User(AbstractUser, PermissionsMixin):
    username = None

    email = models.EmailField(max_length=150, verbose_name='электронная почта', unique=True)
    password = models.CharField(max_length=100, verbose_name='пароль')
    phone = models.CharField(max_length=50, unique=True, verbose_name='номер телефона', null=True, blank=True)
    avatar = models.ImageField(upload_to='user', null=True, blank=True, verbose_name='аватар')
    country = models.CharField(max_length=40, null=True, blank=True, verbose_name='страна')
    verification_code = models.CharField(max_length=6, null=True, blank=True, verbose_name='код подтверждения')
    is_active = models.BooleanField(default=False, verbose_name='признак верификации')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class VerificationCode(models.Model):
    code = models.CharField(max_length=6)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class CustomPermissionsForUser(models.Model):
    class Meta:
        permissions = [
            ("can_block_users", "Can block users")
        ]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from users.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2')


class VerificationForm(forms.Form):
    code = forms.CharField(max_length=6)

users/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView
import random
import string
from django.core.mail import send_mail
from users.forms import UserRegisterForm, VerificationForm
from users.models import User, VerificationCode


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'user/user_form.html'
    success_url = reverse_lazy('users:user_success_registration')

    def form_valid(self, form):
        response = super().form_valid(form)

        code = ''.join(random.choices(string.digits, k=6))

        user = self.object
        user.verification_code = code
        user.save()

        verification_code = VerificationCode.objects.create(code=code, user=user)

        subject = 'Код подтверждения'
        message = f'Ваш код подтверждения {code}'
        sender_email = 'noreplyskypro9@gmail.com'
        recipient_list = [user.email]
        send_mail(subject, message, sender_email, recipient_list)

        return response

    def get_success_url(self):
        return reverse('users:success_regist')


def success_view(request):
    return render(request, 'user/user_success_registration.html')


class VerifyCodeView(View):
    template_name = 'user/user_verify.html'
    form_class = VerificationForm

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            code = form.cleaned_data.get('code')

            try:
                verification_code = VerificationCode.objects.get(code=code)
                user = verification_code.user
                user.is_active = True
                user.save()
                messages.success(request, 'Регистрация прошла успешно!')
                verification_code.delete()
                return HttpResponseRedirect(reverse('main:home'))
            except VerificationCode.DoesNotExist:
                messages.error(request, 'Неправильный код верификации.')
                return render(request, self.template_name, {'form': form})
        else:
            messages.error(request, 'Пожалуйста, введите правильный код верификации.')
        return render(request, self.template_name, {'form': form})


    def get_success_url(self):
        return reverse('main:home')


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return render(request, 'reset_password.html', {'error_message': 'Пользователя с таким email нет'})

        new_password = ''.join(random.choices(string.ascii_letters + string.digits, k=12))

        user.set_password(new_password)
        user.save()

        subject = 'Новый пароль'
        message = f'Ваш новый пароль: {new_password}'
        from_email = 'noreplyskypro9@gmail.com'
        recipient_list = [email]

        send_mail(subject, message, from_email, recipient_list)

        return render(request, 'user/password_reset_done.html')

    return render(request, 'user/reset_password.html')

users/templates/user/password_reset_done.html
{% extends 'main/base.html' %}

{% block content %}

<a>На email был выслан новый пароль, проверьте почту.</a>

{% endblock %}

users/templates/user/reset_password.html
{% extends 'main/base.html' %}


{% block content %}
<form method="post">
    {% csrf_token %}
    <label for="email">Введите свой email:</label>
    <input type="email" id="email" name="email" required>
    <input type="submit" value="Reset Password">
</form>
{% if error_message %}
    <p>{{ error_message }}</p>
{% endif %}

{% endblock %}

users/templates/user/user_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

users/templates/user/user_login.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Войти></button>
                    </form>
                </div>
                <a href="{% url 'users:reset_password' %}" class="btn btn-warning">Забыли пароль?</a>
            </div>
        </div>
    </div>
<div>
{% endblock %}

users/templates/user/user_success_registration.html
{% extends 'main/base.html' %}
{% load static %}

{% block content%}
</head>
<link href={% static 'css/success_registration.css' %} rel="stylesheet">
<body>
    <div class="container">
        <h1>Успешная регистрация!</h1>
        <p>Спасибо за регистрацию на нашем сайте. Пожалуйста, подтвердите свой адрес электронной почты, чтобы активировать свою учетную запись.</p>
        <a href="{% url 'users:verify_code' %}" class="button">Подтвердить почту</a>
    </div>
</body>
</html>

{% endblock %}

users/templates/user/user_verify.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Подтвердить></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}