blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [path('create/', BlogCreateView.as_view(), name='blog_create'),
               path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
               path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
               path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
               path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete')
               ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import MailingDeleteView, MailingListView, ClientCreateView, MessageCreateView, \
    ClientDeleteView, ClientListView, MessageListView, MessageDeleteView, create_mailing, LogsOfMailingListView, home

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('mail/', MailingListView.as_view(), name='mail_list'),
    path('mail/create', cache_page(60)(create_mailing), name='mail_create'),
    path('mail/delete/<int:pk>/', MailingDeleteView.as_view(), name='mail_delete'),
    path('clients/create', ClientCreateView.as_view(), name='client_create'),
    path('message/create', MessageCreateView.as_view(), name='message_create'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('logs/', LogsOfMailingListView.as_view(), name='logs_list')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, VerifyCodeView, success_view, reset_password
from users.models import User

app_name = 'users'

urlpatterns = [path('registration/', UserCreateView.as_view(), name='user_create'),
               path('verify/', VerifyCodeView.as_view(), name='verify_code'),
               path('registration/success/', success_view, name='success_regist'),
               path('login/', LoginView.as_view(template_name='user/user_login.html'), name='login'),
               path('logout/', LogoutView.as_view(template_name='user/user_logout.html'), name='logout'),
               path('reset_password/', reset_password, name='reset_password')]

main/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from users.models import User


class SelectFrequency(models.Model):
    select_frequency = models.CharField(max_length=50, verbose_name='переодичность')

    def __str__(self):
        return self.select_frequency

    class Meta:
        verbose_name = 'переодичность'
        verbose_name_plural = 'переодичности'


class Client(models.Model):
    email = models.EmailField(max_length=150, verbose_name='email')
    first_name = models.CharField(max_length=100, verbose_name='имя')
    second_name = models.CharField(max_length=150, verbose_name='фамилия')
    comment = models.CharField(max_length=200, verbose_name='комментарий')
    owner_clients = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='владелец клиента рассылки', null=True,
                              blank=True)

    def __str__(self):
        return f'{self.first_name} {self.second_name} ({self.email})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mailing(models.Model):
    date = models.DateTimeField(default=timezone.now, verbose_name='дата и время рассылки')
    frequency = models.ForeignKey('SelectFrequency', on_delete=models.PROTECT, verbose_name='переодичность рассылки')
    status = models.CharField(default='создана', max_length=50, verbose_name='статус рассылки')
    client = models.ManyToManyField('Client', verbose_name='клиент для рассылки')
    message = models.ForeignKey('Message', on_delete=models.PROTECT, verbose_name='сообщение для рассылки', null=True,
                                blank=True)
    next_send_date = models.DateTimeField(null=True, blank=True, verbose_name='дата следующей рассылки')
    owner = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, verbose_name='владелец рассылки', null=True, blank=True)

    def __str__(self):
        return f'{self.date},{self.time}, {self.frequency}, {self.status}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class Message(models.Model):
    subject_of_letter = models.CharField(max_length=200, verbose_name='тема письма')
    body_of_letter = models.TextField(verbose_name='тело письма')

    def __str__(self):
        return f'{self.subject_of_letter}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class LogsOfMailing(models.Model):
    date = models.DateTimeField(verbose_name='дата и время логов рассылки')
    status = models.BooleanField(default=False, verbose_name='статус рассылки')
    answer_from_service = models.CharField(max_length=100, verbose_name='ответ от почтового сервера')
    message = models.ForeignKey('Message', on_delete=models.PROTECT, verbose_name='ссылка на сообщение', null=True,
                                blank=True)

    def __str__(self):
        return f'{self.date}, {self.time}, {self.status}, {self.answer_from_service}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'


class CustomPermissions(models.Model):
    class Meta:
        permissions = [("can_disable_mailing", "Can disable mailing")]

main/forms.py
from django import forms

from main.models import Mailing, Client, Message


class MailingCreateForm(forms.ModelForm):
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Mailing
        fields = ('date', 'frequency', 'message', 'clients')

    def save(self, commit=True):
        mailing = super().save(commit=False)
        mailing.owner = self.request.user
        mailing.save()
        mailing.client.set(self.cleaned_data['clients'])
        return mailing


class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('email', 'first_name', 'second_name', 'comment',)


class MessageCreateForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

main/templates/main/views.py
from datetime import timedelta

from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView, DeleteView

from main.forms import MailingCreateForm, ClientCreateForm, MessageCreateForm
from main.models import Mailing, Client, Message, LogsOfMailing
from main.runapscheduler import scheduler, send_mailing


class MailingListView(ListView):
    model = Mailing
    template_name = 'main/home.html'


class MailingCreateView(CreateView):
    model = Mailing
    template_name = 'main/mailing_form.html'
    form_class = MailingCreateForm
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        response = super().form_valid(form)

        email_for_mail = self.object.client.email
        subject_of_mail = self.object.message.subject_of_letter
        body_of_message = self.object.message.body_of_letter

        subject = subject_of_mail
        message = body_of_message
        sender_email = 'noreplyskypro9@gmail.com'
        recipient_list = [email_for_mail]
        send_mail(subject, message, sender_email, recipient_list)

        return response


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:home')
    template_name = 'main/mailing_confirm_delete.html'


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientCreateForm
    success_url = reverse_lazy('main:client_list')


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')


class ClientListView(ListView):
    model = Client


class MessageListView(ListView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageCreateForm
    success_url = reverse_lazy('main:message_list')


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('main:message_list')


class LogsOfMailingListView(ListView):
    model = LogsOfMailing


def create_mailing(request):
    if request.method == 'POST':
        form = MailingCreateForm(request.POST)
        if form.is_valid():
            mailing = form.save()


            if mailing.frequency.select_frequency == 'один раз в день':
                next_send_date = mailing.date
            elif mailing.frequency.select_frequency == 'один раз в неделю':
                next_send_date = mailing.date + timedelta(weeks=1)
            elif mailing.frequency.select_frequency == 'один раз в месяц':
                next_send_date = mailing.date + timedelta(days=30)
            mailing.next_send_date = next_send_date
            mailing.save()

            scheduler.add_job(send_mailing, 'date', run_date=mailing.next_send_date, args=[mailing.id])

            return redirect('main:home')
    else:
        form = MailingCreateForm()
    return render(request, 'main/mailing_form.html', {'form': form})

main/views.py
from datetime import timedelta
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView

from blog.models import Blog
from main.forms import MailingCreateForm, ClientCreateForm, MessageCreateForm
from main.models import Mailing, Client, Message, LogsOfMailing
from main.runapscheduler import scheduler, send_mailing, schedule_mailing


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    template_name = 'main/mailing_list.html'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:mail_list')
    template_name = 'main/mailing_confirm_delete.html'

    def get_queryset(self):
        return Mailing.objects.filter(owner=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientCreateForm
    success_url = reverse_lazy('main:client_list')

    def form_valid(self, form):
        form.instance.owner_clients = self.request.user
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')

    def get_queryset(self):
        return Client.objects.filter(owner_clients=self.request.user)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'main/client_list.html'

    def get_queryset(self):
        return Client.objects.filter(owner_clients=self.request.user)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageCreateForm
    success_url = reverse_lazy('main:message_list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('main:message_list')


class LogsOfMailingListView(LoginRequiredMixin, ListView):
    model = LogsOfMailing


@login_required
def create_mailing(request):
    if request.method == 'POST':
        form = MailingCreateForm(request.POST, request=request)
        if form.is_valid():
            mailing = form.save(commit=False)

            if mailing.frequency.select_frequency == 'один раз в день':
                next_send_date = mailing.date + timedelta(days=1)
            elif mailing.frequency.select_frequency == 'один раз в неделю':
                next_send_date = mailing.date + timedelta(weeks=1)
            elif mailing.frequency.select_frequency == 'один раз в месяц':
                next_send_date = mailing.date + timedelta(days=30)

            mailing.next_send_date = next_send_date
            mailing.save()

            recipients = form.cleaned_data['clients'].values_list('email', flat=True)

            schedule_mailing(mailing.id, mailing.next_send_date, mailing.frequency.select_frequency, recipients)

            send_mailing(mailing.id, recipients)

            return redirect('main:mail_list')
    else:
        clients = Client.objects.all()
        form = MailingCreateForm(initial={'clients': clients}, request=request)
    return render(request, 'main/mailing_form.html', {'form': form})



def home(request):
    total_mailings = Mailing.objects.count()

    active_mailings = Mailing.objects.filter(status='активна').count()

    unique_clients = Client.objects.filter(mailing__isnull=False).distinct().count()

    blog =Blog.objects.all()
    random_blog = random.sample(list(blog), min(len(blog), 3))

    context = {
        'total_mailings': total_mailings,
        'active_mailings': active_mailings,
        'unique_clients': unique_clients,
        'random_blog': random_blog,
    }

    return render(request, 'main/home.html', context)

main/templates/main/base.html
{% load static %}
{% block menu %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Рассылки</title>
    <link rel="stylesheet" href="{% static 'css/navigation_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/object_styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/btn_styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <a class="btn" href="{% url 'main:home'%}">Главная</a>
                <a class="btn" href="{% url 'main:mail_list'%}">Рассылки</a>
                <a class="btn" href="{% url 'main:logs_list' %}">Отчет</a>
                <a class="btn" href="{% url 'main:client_list' %}">Пользователи</a>
                <a class="btn" href="{% url 'main:message_list' %}">Сообщения</a>
                <a class="btn" href="{% url 'blog:blog_list' %}">Блог</a>
                {% if user.is_authenticated %}
               <a class="btn logout-btn" href="{% url 'users:logout'%}">Выход</a>
                {% else %}
                <a class="btn login-btn" href="{% url 'users:login'%}">Вход</a>
                <a class="btn registration-btn" href="/users/registration">Регистрация</a>
                {% endif %}
            </ul>
        </nav>
    </header>
{% endblock %}

{% block content%}

{% endblock %}

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<title>Удаление рассылки</title>
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить клиента {{ object.first_name}} {{ object.second_name}} ({{ object.email}})?</p>
                            <button type="submit" name="confirm" value="{{ object.id }}" class="btn btn-warning">Подтвердить</button>
                            <a href="{% url 'main:home' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="text-center mt-4">
        <a href="{% url 'main:client_create' %}" class="btn btn-primary btn-lg">Создать пользователя</a>
    </div>

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text"> Имя: {{ object.first_name }}</p>
                    <p class="card-text">Фамилия: {{ object.second_name }}</p>
                    <p class="card-text"> Эл. почта: {{ object.email }}</p>
                    <p class="card-text">Комментарий: {{ object.comment }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'main:client_delete' pk=object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/home_styles.css' %}">
{% block content %}
    <title>Главная страница</title>
<body>
    <h1>Главная страница</h1>
    <p>Всего рассылок: {{ total_mailings }}</p>
    <p>Активных рассылок: {{ active_mailings }}</p>
    <p>Уникальных клиентов для рассылок: {{ unique_clients }}</p>

    <h2>Случайные статьи из блога:</h2>
    <ul>
        {% for blog in random_blog %}
            <li><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>
{% endblock %}

main/templates/main/logsofmailing_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="text-center mt-4">
    </div>

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text"> дата: {{ object.date }}</p>
                    <p class="card-text">Статус {{ object.status }}</p>
                    <p class="card-text"> Ответ от сервиса {{ object.answer_from_service }}</p>
                    <p class="card-text">Сообщение {{ object.mailing }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'main:client_delete' pk=object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<title>Удаление рассылки</title>
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить рассылку?</p>
                            <button type="submit" name="confirm" value="{{ object.id }}" class="btn btn-warning">Подтвердить</button>
                            <a href="{% url 'main:mail_list' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="text-center mt-4">
        <a href="{% url 'main:mail_create' %}" class="btn btn-primary btn-lg">Создать рассылку</a>
    </div>

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text"> Дата: {{ object.date }}</p>
                    <p class="card-text">Переодичность рассылки: {{ object.frequency }}</p>
                    <p class="card-text"> Статус: {{ object.status }}</p>
                    <p class="card-text">Клиенты: {{ object.client.email }}</p>
                    <p class="card-text">Письмо: {{ object.message }}</p>
                    <p class="card-text">дата след. отправки: {{ object.next_send_date }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'main:mail_delete' pk=object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/message_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<title>Удаление рассылки</title>
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить сообщение с темой "{{ object.subject_of_letter }}"?</p>
                            <button type="submit" name="confirm" value="{{ object.id }}" class="btn btn-warning">Подтвердить</button>
                            <a href="{% url 'main:home' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/message_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Создать></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="text-center mt-4">
        <a href="{% url 'main:message_create' %}" class="btn btn-primary btn-lg">Создать сообщение</a>
    </div>

    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text"> Тема:{{ object.subject_of_letter }}</p>
                    <p class="card-text">Тело письма: {{ object.body_of_letter }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'main:message_delete' pk=object.pk %}" class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}